apiVersion: v1
kind: Secret
metadata:
  name: kafka-bridge-tls
  namespace: default
  labels:
    app: kafka-bridge
stringData:
  ca.pem: |
    # PEM-encoded CA cert
  client-cert.pem: |
    # PEM-encoded client certificate
  client-key.pem: |
    # PEM-encoded client key
